import type { CSSProperties, ComponentType, SVGProps } from "react";
import AccessTimeRoundedIcon from "@mui/icons-material/AccessTimeRounded";
import AccountBalanceWalletRoundedIcon from "@mui/icons-material/AccountBalanceWalletRounded";
import AccountCircleRoundedIcon from "@mui/icons-material/AccountCircleRounded";
import AddRoundedIcon from "@mui/icons-material/AddRounded";
import AdsClickRoundedIcon from "@mui/icons-material/AdsClickRounded";
import AirRoundedIcon from "@mui/icons-material/AirRounded";
import ApartmentRoundedIcon from "@mui/icons-material/ApartmentRounded";
import ArrowBackRoundedIcon from "@mui/icons-material/ArrowBackRounded";
import ArrowCircleDownRoundedIcon from "@mui/icons-material/ArrowCircleDownRounded";
import ArrowCircleUpRoundedIcon from "@mui/icons-material/ArrowCircleUpRounded";
import ArrowForwardRoundedIcon from "@mui/icons-material/ArrowForwardRounded";
import AutorenewRoundedIcon from "@mui/icons-material/AutorenewRounded";
import AutoAwesomeRoundedIcon from "@mui/icons-material/AutoAwesomeRounded";
import BarChartRoundedIcon from "@mui/icons-material/BarChartRounded";
import BoltRoundedIcon from "@mui/icons-material/BoltRounded";
import BuildRoundedIcon from "@mui/icons-material/BuildRounded";
import CalendarMonthRoundedIcon from "@mui/icons-material/CalendarMonthRounded";
import CallRoundedIcon from "@mui/icons-material/CallRounded";
import CancelRoundedIcon from "@mui/icons-material/CancelRounded";
import ChatBubbleOutlineRoundedIcon from "@mui/icons-material/ChatBubbleOutlineRounded";
import ChatRoundedIcon from "@mui/icons-material/ChatRounded";
import CheckCircleRoundedIcon from "@mui/icons-material/CheckCircleRounded";
import CheckRoundedIcon from "@mui/icons-material/CheckRounded";
import ChevronLeftRoundedIcon from "@mui/icons-material/ChevronLeftRounded";
import ChevronRightRoundedIcon from "@mui/icons-material/ChevronRightRounded";
import CloseRoundedIcon from "@mui/icons-material/CloseRounded";
import CreditCardRoundedIcon from "@mui/icons-material/CreditCardRounded";
import DashboardRoundedIcon from "@mui/icons-material/DashboardRounded";
import DateRangeRoundedIcon from "@mui/icons-material/DateRangeRounded";
import DeleteOutlineRoundedIcon from "@mui/icons-material/DeleteOutlineRounded";
import DescriptionRoundedIcon from "@mui/icons-material/DescriptionRounded";
import DirectionsCarRoundedIcon from "@mui/icons-material/DirectionsCarRounded";
import DiscFullRoundedIcon from "@mui/icons-material/DiscFullRounded";
import EditRoundedIcon from "@mui/icons-material/EditRounded";
import ErrorOutlineRoundedIcon from "@mui/icons-material/ErrorOutlineRounded";
import EventRoundedIcon from "@mui/icons-material/EventRounded";
import EventSeatRoundedIcon from "@mui/icons-material/EventSeatRounded";
import ExpandLessRoundedIcon from "@mui/icons-material/ExpandLessRounded";
import ExpandMoreRoundedIcon from "@mui/icons-material/ExpandMoreRounded";
import FactCheckRoundedIcon from "@mui/icons-material/FactCheckRounded";
import FilterListRoundedIcon from "@mui/icons-material/FilterListRounded";
import GridViewRoundedIcon from "@mui/icons-material/GridViewRounded";
import GroupsRoundedIcon from "@mui/icons-material/GroupsRounded";
import HeadsetMicRoundedIcon from "@mui/icons-material/HeadsetMicRounded";
import HistoryRoundedIcon from "@mui/icons-material/HistoryRounded";
import InfoRoundedIcon from "@mui/icons-material/InfoRounded";
import AddCommentRoundedIcon from "@mui/icons-material/AddCommentRounded";
import AddPhotoAlternateRoundedIcon from "@mui/icons-material/AddPhotoAlternateRounded";
import AttachMoneyRoundedIcon from "@mui/icons-material/AttachMoneyRounded";
import LensRoundedIcon from "@mui/icons-material/LensRounded";
import LocalActivityRoundedIcon from "@mui/icons-material/LocalActivityRounded";
import LocalGasStationRoundedIcon from "@mui/icons-material/LocalGasStationRounded";
import LockRoundedIcon from "@mui/icons-material/LockRounded";
import LogoutRoundedIcon from "@mui/icons-material/LogoutRounded";
import MailRoundedIcon from "@mui/icons-material/MailRounded";
import MenuBookRoundedIcon from "@mui/icons-material/MenuBookRounded";
import MenuRoundedIcon from "@mui/icons-material/MenuRounded";
import MonetizationOnRoundedIcon from "@mui/icons-material/MonetizationOnRounded";
import MoreHorizRoundedIcon from "@mui/icons-material/MoreHorizRounded";
import MoreVertRoundedIcon from "@mui/icons-material/MoreVertRounded";
import NotificationsRoundedIcon from "@mui/icons-material/NotificationsRounded";
import OpenInNewRoundedIcon from "@mui/icons-material/OpenInNewRounded";
import PaymentsRoundedIcon from "@mui/icons-material/PaymentsRounded";
import PersonAddRoundedIcon from "@mui/icons-material/PersonAddRounded";
import PersonRoundedIcon from "@mui/icons-material/PersonRounded";
import PlayArrowRoundedIcon from "@mui/icons-material/PlayArrowRounded";
import PhoneInTalkRoundedIcon from "@mui/icons-material/PhoneInTalkRounded";
import PowerRoundedIcon from "@mui/icons-material/PowerRounded";
import PowerSettingsNewRoundedIcon from "@mui/icons-material/PowerSettingsNewRounded";
import RadioButtonUncheckedRoundedIcon from "@mui/icons-material/RadioButtonUncheckedRounded";
import ReplayRoundedIcon from "@mui/icons-material/ReplayRounded";
import ScheduleRoundedIcon from "@mui/icons-material/ScheduleRounded";
import SearchRoundedIcon from "@mui/icons-material/SearchRounded";
import SendRoundedIcon from "@mui/icons-material/SendRounded";
import SettingsRoundedIcon from "@mui/icons-material/SettingsRounded";
import ShareRoundedIcon from "@mui/icons-material/ShareRounded";
import ShieldRoundedIcon from "@mui/icons-material/ShieldRounded";
import SpeedRoundedIcon from "@mui/icons-material/SpeedRounded";
import StarRoundedIcon from "@mui/icons-material/StarRounded";
import TaskAltRoundedIcon from "@mui/icons-material/TaskAltRounded";
import TrendingDownRoundedIcon from "@mui/icons-material/TrendingDownRounded";
import TrendingUpRoundedIcon from "@mui/icons-material/TrendingUpRounded";
import TuneRoundedIcon from "@mui/icons-material/TuneRounded";
import UploadRoundedIcon from "@mui/icons-material/UploadRounded";
import VerifiedUserRoundedIcon from "@mui/icons-material/VerifiedUserRounded";
import ViewListRoundedIcon from "@mui/icons-material/ViewListRounded";
import ViewSidebarRoundedIcon from "@mui/icons-material/ViewSidebarRounded";
import VisibilityRoundedIcon from "@mui/icons-material/VisibilityRounded";
import WarningAmberRoundedIcon from "@mui/icons-material/WarningAmberRounded";

type LucideProps = SVGProps<SVGSVGElement> & { size?: number | string };
export type LucideIcon = ComponentType<LucideProps>;

function adapt(Icon: ComponentType<any>): LucideIcon {
  return function LucideMuiIcon({ size, style, ...props }: LucideProps) {
    const sizedStyle: CSSProperties | undefined = size
      ? {
          width: typeof size === "number" ? `${size}px` : size,
          height: typeof size === "number" ? `${size}px` : size,
          ...(style ?? {}),
        }
      : style;

    return <Icon {...props} style={sizedStyle} />;
  };
}

export const Activity = adapt(LocalActivityRoundedIcon);
export const AlertCircle = adapt(ErrorOutlineRoundedIcon);
export const AlertTriangle = adapt(WarningAmberRoundedIcon);
export const Armchair = adapt(EventSeatRoundedIcon);
export const ArrowDownCircle = adapt(ArrowCircleDownRoundedIcon);
export const ArrowDownLeft = adapt(ArrowCircleDownRoundedIcon);
export const ArrowLeft = adapt(ArrowBackRoundedIcon);
export const ArrowRight = adapt(ArrowForwardRoundedIcon);
export const ArrowUpCircle = adapt(ArrowCircleUpRoundedIcon);
export const ArrowUpRight = adapt(ArrowCircleUpRoundedIcon);
export const Banknote = adapt(PaymentsRoundedIcon);
export const BarChart3 = adapt(BarChartRoundedIcon);
export const Bell = adapt(NotificationsRoundedIcon);
export const BookOpen = adapt(MenuBookRoundedIcon);
export const Building2 = adapt(ApartmentRoundedIcon);
export const Calendar = adapt(CalendarMonthRoundedIcon);
export const CalendarClock = adapt(EventRoundedIcon);
export const CalendarDays = adapt(CalendarMonthRoundedIcon);
export const CalendarRange = adapt(DateRangeRoundedIcon);
export const Camera = adapt(EventRoundedIcon);
export const Car = adapt(DirectionsCarRoundedIcon);
export const CarFront = adapt(DirectionsCarRoundedIcon);
export const Check = adapt(CheckRoundedIcon);
export const CheckCircle = adapt(CheckCircleRoundedIcon);
export const CheckCircle2 = adapt(TaskAltRoundedIcon);
export const ChevronDown = adapt(ExpandMoreRoundedIcon);
export const ChevronDownIcon = adapt(ExpandMoreRoundedIcon);
export const ChevronLeft = adapt(ChevronLeftRoundedIcon);
export const ChevronLeftIcon = adapt(ChevronLeftRoundedIcon);
export const ChevronRight = adapt(ChevronRightRoundedIcon);
export const ChevronRightIcon = adapt(ChevronRightRoundedIcon);
export const ChevronUp = adapt(ExpandLessRoundedIcon);
export const Circle = adapt(RadioButtonUncheckedRoundedIcon);
export const CircleDollarSign = adapt(MonetizationOnRoundedIcon);
export const ClipboardCheck = adapt(FactCheckRoundedIcon);
export const Clock = adapt(AccessTimeRoundedIcon);
export const Clock3 = adapt(ScheduleRoundedIcon);
export const CreditCard = adapt(CreditCardRoundedIcon);
export const Disc3 = adapt(DiscFullRoundedIcon);
export const Edit2 = adapt(EditRoundedIcon);
export const ExternalLink = adapt(OpenInNewRoundedIcon);
export const Eye = adapt(VisibilityRoundedIcon);
export const FileCheck = adapt(TaskAltRoundedIcon);
export const FileText = adapt(DescriptionRoundedIcon);
export const Filter = adapt(FilterListRoundedIcon);
export const Fuel = adapt(LocalGasStationRoundedIcon);
export const Gauge = adapt(SpeedRoundedIcon);
export const HandCoins = adapt(AttachMoneyRoundedIcon);
export const Headphones = adapt(HeadsetMicRoundedIcon);
export const History = adapt(HistoryRoundedIcon);
export const ImagePlus = adapt(AddPhotoAlternateRoundedIcon);
export const Info = adapt(InfoRoundedIcon);
export const LayoutDashboard = adapt(DashboardRoundedIcon);
export const LayoutGrid = adapt(GridViewRoundedIcon);
export const List = adapt(ViewListRoundedIcon);
export const Loader2 = adapt(AutorenewRoundedIcon);
export const Lock = adapt(LockRoundedIcon);
export const LogOut = adapt(LogoutRoundedIcon);
export const Mail = adapt(MailRoundedIcon);
export const Menu = adapt(MenuRoundedIcon);
export const MessageCircle = adapt(ChatRoundedIcon);
export const MessageCircleMore = adapt(AddCommentRoundedIcon);
export const MessageSquare = adapt(ChatBubbleOutlineRoundedIcon);
export const MoreHorizontal = adapt(MoreHorizRoundedIcon);
export const MoreVertical = adapt(MoreVertRoundedIcon);
export const MousePointerClick = adapt(AdsClickRoundedIcon);
export const PanelLeft = adapt(ViewSidebarRoundedIcon);
export const PanelLeftClose = adapt(ViewSidebarRoundedIcon);
export const Pencil = adapt(EditRoundedIcon);
export const Phone = adapt(CallRoundedIcon);
export const PhoneCall = adapt(PhoneInTalkRoundedIcon);
export const Play = adapt(PlayArrowRoundedIcon);
export const Plus = adapt(AddRoundedIcon);
export const Power = adapt(PowerRoundedIcon);
export const PowerOff = adapt(PowerSettingsNewRoundedIcon);
export const RotateCcw = adapt(ReplayRoundedIcon);
export const Search = adapt(SearchRoundedIcon);
export const Send = adapt(SendRoundedIcon);
export const Settings = adapt(SettingsRoundedIcon);
export const Settings2 = adapt(TuneRoundedIcon);
export const Share2 = adapt(ShareRoundedIcon);
export const Shield = adapt(ShieldRoundedIcon);
export const ShieldCheck = adapt(VerifiedUserRoundedIcon);
export const SlidersHorizontal = adapt(TuneRoundedIcon);
export const Sparkles = adapt(AutoAwesomeRoundedIcon);
export const Star = adapt(StarRoundedIcon);
export const Trash2 = adapt(DeleteOutlineRoundedIcon);
export const TrendingDown = adapt(TrendingDownRoundedIcon);
export const TrendingUp = adapt(TrendingUpRoundedIcon);
export const Upload = adapt(UploadRoundedIcon);
export const User = adapt(PersonRoundedIcon);
export const UserPlus = adapt(PersonAddRoundedIcon);
export const UserRound = adapt(AccountCircleRoundedIcon);
export const Users = adapt(GroupsRoundedIcon);
export const Wallet = adapt(AccountBalanceWalletRoundedIcon);
export const Wind = adapt(AirRoundedIcon);
export const Wrench = adapt(BuildRoundedIcon);
export const X = adapt(CloseRoundedIcon);
export const XCircle = adapt(CancelRoundedIcon);
export const Zap = adapt(BoltRoundedIcon);
export const CheckIcon = adapt(CheckRoundedIcon);
export const Lens = adapt(LensRoundedIcon);
