ALTER TABLE "users"
ADD COLUMN IF NOT EXISTS "isActive" BOOLEAN NOT NULL DEFAULT true,
ADD COLUMN IF NOT EXISTS "invitedAt" TIMESTAMP(3),
ADD COLUMN IF NOT EXISTS "invitedById" TEXT,
ADD COLUMN IF NOT EXISTS "lastLoginAt" TIMESTAMP(3);

ALTER TABLE "users"
ALTER COLUMN "role" SET DEFAULT 'EMPLOYEE';

CREATE INDEX IF NOT EXISTS "users_agencyId_role_idx" ON "users"("agencyId", "role");
